import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Braces, Database, KeyRound, LockKeyhole, ShieldCheck, Waypoints } from "lucide-react";
import { Kicker, NextStep, PageHero } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Architecture", description: "The Voltaris architecture: two Next.js products, shared domain logic, PostgreSQL, Gemini, human approval, and isolated reviewer workspaces."};

const boundaries = [
  {icon: ShieldCheck, title: "Human approval", copy: "AI can propose an action. A signed-in staff member must approve the dispatch before booking and forecast posting."},
  {icon: Database, title: "Deterministic accounting", copy: "Margin uses fixed, parameterized queries. Forecast events and actual postings have separate meanings in the domain model."},
  {icon: LockKeyhole, title: "Reviewer isolation", copy: "Each invited reviewer operates in an account-owned PostgreSQL schema with an explicit reset and expiry."},
  {icon: Braces, title: "Validated model output", copy: "Command checks exact source IDs on each claim. Invalid claims are discarded; an uncertain fallback is preserved."},
];

export default function ArchitecturePage() { return <>
  <PageHero number="04" eyebrow="SYSTEM DESIGN" title="Intelligence with" accent="clear boundaries" description="The architecture separates suggestion from authority, forecast from actual, and one reviewer's workspace from another's." image="/media/operations-room.webp" visual={<div className="hero-system-card" aria-label="Architecture boundary from staff approval through shared core to persistent records"><div className="hero-system-top"><span>CONTROL PATH</span><span>VOLTARIS / SYSTEM</span></div><div className="hero-system-row"><ShieldCheck/><div><strong>Staff authorizes</strong><small>Human approval remains the action boundary</small></div><span>01</span></div><div className="hero-system-row"><Waypoints/><div><strong>@voltaris/core</strong><small>Rules, transactions, and validated AI output</small></div><span>02</span></div><div className="hero-system-row"><Database/><div><strong>PostgreSQL records</strong><small>Booking, work order, forecast, and audit</small></div><span>03</span></div><div className="hero-system-foot">ONE APPROVAL · ONE TRANSACTION · TRACEABLE RESULT</div></div>}><a className="button button-outline-light" href="https://github.com/code-cra7t/voltaris-energy-platform" target="_blank" rel="noreferrer">Explore the repository <ArrowUpRight size={18}/></a></PageHero>
  <section className="section-paper architecture-section"><div className="container"><Reveal><Kicker number="01">ONE PLATFORM / TWO PRODUCTS</Kicker><h2>Connected where it matters.<br/><em>Separate where it helps.</em></h2><p className="section-lead">Command and Margin are separate Next.js applications. A shared TypeScript core owns authentication, domain rules, database operations, Gemini integration, and state transitions. Both products read the same workspace data.</p></Reveal><div className="architecture-diagram" role="img" aria-label="Voltaris staff use Command and Margin; both connect through the shared core to Neon PostgreSQL and Gemini, with human approval required for dispatch"><div className="arch-top"><span>VOLTARIS STAFF</span><small>Authenticated, account-owned workspace</small></div><div className="arch-branch"><div className="arch-app"><span>OPERATIONS</span><strong>Command</strong><small>Incident → evidence → proposal → approval → work order</small></div><div className="arch-app"><span>INTELLIGENCE</span><strong>Margin</strong><small>Posted actuals → backlog → evidence-backed analysis</small></div></div><div className="arch-core"><Waypoints size={23}/><div><span>SHARED SERVICE LAYER</span><strong>@voltaris/core</strong></div><small>Auth · state transitions · calculations · transactions</small></div><div className="arch-bottom"><div><Database size={22}/><strong>Neon PostgreSQL</strong><span>Persistent records + isolated schemas</span></div><div><Braces size={22}/><strong>Gemini</strong><span>Advisory analysis + explanations</span></div></div></div></div></section>
  <section className="section-ink boundary-section"><div className="container"><Reveal><Kicker number="02" light>DESIGNED LIMITS</Kicker><h2>The rules that make<br/><em>the workflow credible.</em></h2></Reveal><div className="boundary-grid">{boundaries.map((item, i) => <Reveal key={item.title} delay={i * 60}><div className="boundary-item"><item.icon size={28}/><span>0{i + 1} / GUARANTEE</span><h3>{item.title}</h3><p>{item.copy}</p></div></Reveal>)}</div></div></section>
  <section className="section-paper architecture-details"><div className="container"><Reveal><Kicker number="03">WHAT HAPPENS ON APPROVAL</Kicker><h2>A state change with<br/><em>one commit.</em></h2></Reveal><div className="transaction-list"><div><span>01</span><strong>Validate</strong><p>Confirm the proposal, staff authority, and technician-slot availability.</p></div><div><span>02</span><strong>Book</strong><p>Reserve the qualified slot and create the service work order.</p></div><div><span>03</span><strong>Account</strong><p>Post the forecast-cost event for Margin's open backlog.</p></div><div><span>04</span><strong>Audit</strong><p>Record the decision and commit everything in one PostgreSQL transaction.</p></div></div><div className="technical-note"><KeyRound/><p>Production secrets stay server-side. Request traces include operation and timing details without logging credentials, prompts, or SQL values. The public site itself holds no staff credentials.</p></div><Link href="/case-study" className="large-inline-link">Read the engineering case study <ArrowUpRight size={21}/></Link></div></section>
  <NextStep eyebrow="FROM DESIGN TO EXPERIENCE" title="See the decisions in action." description="Enter an isolated reviewer workspace and follow the Hannover incident from evidence through approval to financial consequence." href="/reviewer" label="Launch reviewer workspace"/>
</>; }
