import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Clock3, RotateCcw, ShieldCheck } from "lucide-react";
import { Kicker, PageHero } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Reviewer workspace", description: "Enter private Voltaris workspaces to investigate a charger fault in Command and follow its cost in Margin."};

export default function ReviewerPage() { return <>
  <PageHero number="07" eyebrow="YOUR WORKSPACE" title="Take the next" accent="operational decision" description="Step into a private simulated shift. Investigate the Hannover charger fault in Command, approve a response, and see its financial consequence in Margin." image="/media/charging-hub-dusk.webp" visual={<div className="hero-shift-card"><div className="hero-shift-status"><span className="signal-dot"/> REVIEWER SHIFT / READY</div><strong>Hannover connector fault</strong><p>One incident. Two products. A decision you can trace.</p><div><span>01</span><span>Investigate in Command</span><ArrowRight size={16}/></div><div><span>02</span><span>Approve the response</span><ArrowRight size={16}/></div><div><span>03</span><span>See the result in Margin</span><ArrowRight size={16}/></div><small>PRIVATE WORKSPACE · SYNTHETIC RECORDS</small></div>}><a href="#start" className="button button-light">Start the journey <ArrowDown size={18}/></a></PageHero>
  <section className="section-paper reviewer-start" id="start"><div className="container"><Reveal><Kicker number="01">BEFORE YOU BEGIN</Kicker><h2>Your shift is ready<span className="orange-period">.</span></h2><p className="section-lead">Use the invited Voltaris email and password provided privately. The same account works in both products. Their separate web addresses require a sign-in on each one.</p></Reveal><div className="reviewer-notes"><div><ShieldCheck/><strong>Private workspace</strong><span>Your actions persist for your account only.</span></div><div><RotateCcw/><strong>Safe to explore</strong><span>Restore shift state returns your workspace to its starting records.</span></div><div><Clock3/><strong>A real sequence</strong><span>Allow about 5–10 minutes to inspect the full workflow.</span></div></div></div></section>
  <section className="section-ink reviewer-route atmospheric-reviewer"><div className="container"><Reveal><Kicker number="02" light>THE ROUTE</Kicker><h2>One shift.<br/><em>Two connected products.</em></h2></Reveal><div className="reviewer-steps"><div className="reviewer-step"><span>01 / COMMAND</span><div><h3>Open the incoming fault.</h3><p>Use the shift handoff to select VC-HAN-001. Review its asset, service history, and contract target. Then select <strong>Analyze incident</strong> and inspect the cited evidence.</p></div><a href="https://voltaris-energy-platform-command.vercel.app/" target="_blank" rel="noreferrer">Open Command <ArrowUpRight size={19}/></a></div><div className="reviewer-step"><span>02 / COMMAND</span><div><h3>Plan, then approve.</h3><p>Select <strong>Build proposal</strong>. Check the proposed technician, slot, response warning, and forecast cost. Only <strong>Approve &amp; schedule</strong> creates the booking and work order.</p></div><a href="https://voltaris-energy-platform-command.vercel.app/" target="_blank" rel="noreferrer">Continue in Command <ArrowUpRight size={19}/></a></div><div className="reviewer-step"><span>03 / MARGIN</span><div><h3>Trace the consequence.</h3><p>Choose <strong>View Hannover backlog</strong>. The new work order appears as forecast cost; actual margin remains unchanged. Complete the job in Command to post an actual cost.</p></div><a href="https://voltaris-energy-platform-margin.vercel.app/" target="_blank" rel="noreferrer">Open Margin <ArrowUpRight size={19}/></a></div></div></div></section>
  <section className="section-paper reviewer-finish"><div className="container"><Reveal><Kicker number="03">KEEP EXPLORING</Kicker><h2>Every action has a record.</h2><p>Try reporting an incident, rejecting a proposal, or examining the audit activity. Your changes stay in your workspace. When you want the original scenario again, choose <strong>Restore shift state</strong> in Command.</p><div className="reviewer-actions"><a href="https://voltaris-energy-platform-command.vercel.app/" className="button button-dark" target="_blank" rel="noreferrer">Launch Command <ArrowUpRight size={17}/></a><a href="https://voltaris-energy-platform-margin.vercel.app/" className="button button-outline-dark" target="_blank" rel="noreferrer">Launch Margin <ArrowUpRight size={17}/></a></div><Link href="/architecture" className="inline-arrow">How the products work <ArrowRight size={17}/></Link></Reveal></div></section>
  <div className="disclosure-bar">Voltaris Energy is fictional. Reviewer accounts operate on synthetic records in private workspaces; no physical energy equipment is controlled.</div>
</>; }
