import type { Metadata } from "next";
import { ArrowUpRight, ChartNoAxesCombined, Database, ScanEye, Waypoints } from "lucide-react";
import { ImageFeature, Kicker, NextStep, PageHero } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Margin — revenue and operations intelligence", description: "Evidence-backed service profitability with posted actuals, forecast backlog, and constrained AI explanations."};

export default function MarginPage() { return <>
  <PageHero number="03" eyebrow="PRODUCT / MARGIN" title="Know what the work" accent="really costs" description="Margin connects service activity to performance. It shows posted revenue and actual cost separately from the forecast cost of work still in progress."><a className="button button-primary" href="https://voltaris-energy-platform-margin.vercel.app/" target="_blank" rel="noreferrer">Open live Margin <ArrowUpRight size={18}/></a></PageHero>
  <section className="section-paper product-intro"><div className="container"><Reveal><Kicker number="01">FINANCIAL CONSEQUENCE</Kicker><div className="split-heading"><h2>From a scheduled visit<br/>to a <em>clearer margin.</em></h2><p>When Command creates a work order, Margin sees its forecast service cost in the open backlog. The financial dashboard does not treat that estimate as an actual cost. Completion posts the real event, changing the calculation.</p></div></Reveal><div className="hero-screenshot"><img src="/media/04-margin-overview.jpg" alt="Actual Margin overview showing operating metrics"/><div className="screenshot-caption">ACTUAL PRODUCT CAPTURE / MARGIN OVERVIEW</div></div></div></section>
  <section className="section-ink product-sequence"><div className="container"><Reveal><Kicker number="02" light>THE FINANCIAL MODEL</Kicker><h2>Understand the present.<br/><em>See what is coming.</em></h2></Reveal><div className="sequence-grid three"><Reveal><div><Database/><span>01 / POSTED</span><h3>Actual performance</h3><p>Revenue and service margin are calculated from posted financial events in PostgreSQL.</p></div></Reveal><Reveal delay={70}><div><Waypoints/><span>02 / FORECAST</span><h3>Open backlog</h3><p>Approved unfinished work appears as estimated cost, linked to the source work order.</p></div></Reveal><Reveal delay={140}><div><ScanEye/><span>03 / EXPLAIN</span><h3>Evidence-backed answers</h3><p>AI explains computed figures and linked records. It never writes executable SQL or invents the financial result.</p></div></Reveal></div></div></section>
  <section className="section-paper feature-section"><div className="container"><ImageFeature eyebrow="01 / BACKLOG" title="The scheduled work, in context." body="The approved Hannover visit enters the backlog as an open work order with forecast cost. A second already scheduled job gives the service team a realistic queue to inspect." image="/media/05-margin-backlog.jpg" alt="Margin backlog of approved open service work"/><ImageFeature reverse eyebrow="02 / EXPLANATION" title="Questions grounded in records." body="Ask why performance moved or what sits in the service backlog. Margin constrains the answer to computed figures and traceable operational evidence." image="/media/10-margin-ai-answer.jpg" alt="Margin evidence-backed AI explanation"/></div></section>
  <section className="accounting-band"><div className="container"><Reveal><ChartNoAxesCombined size={30}/><div><span>THE IMPORTANT DISTINCTION</span><h2>Forecast informs a decision.<br/>Actual changes the books.</h2></div></Reveal></div></section>
  <NextStep eyebrow="BEHIND THE PRODUCTS" title="See how the system is built." description="Explore the shared domain layer, transactional approval boundary, reviewer isolation, and the data path between Command and Margin." href="/architecture" label="Explore architecture"/>
</>; }
