import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BadgeCheck, CircleAlert, ListChecks } from "lucide-react";
import { Kicker, NextStep, PageHero } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Case study", description: "The Voltaris product case study: a charger incident connected to evidence, human dispatch, work orders, and service margin."};

export default function CaseStudyPage() { return <>
  <PageHero number="05" eyebrow="PRODUCT CASE STUDY" title="A messy process." accent="One coherent system" description="Voltaris turns a simulated energy-service fault into a working, reviewable chain of decisions across operations and financial intelligence."><Link href="/reviewer" className="button button-primary">Explore the working products <ArrowUpRight size={18}/></Link></PageHero>
  <section className="section-paper case-intro"><div className="container"><Reveal><Kicker number="01">THE SCENARIO</Kicker><h2>A charger keeps failing<br/>at <em>Hannover Messe Hub.</em></h2><p className="section-lead">The service team needs to understand a repeated connector fault, evaluate prior visits and field guidance, find a qualified technician, respect the contract response target, and keep a clean account of what the work costs.</p></Reveal><div className="case-facts"><div><span>ASSET</span><strong>VC-HAN-001</strong><small>Commercial EV charger</small></div><div><span>LOCATION</span><strong>Hannover</strong><small>Messe Hub</small></div><div><span>STARTING STATE</span><strong>Open fault</strong><small>Awaiting investigation</small></div><div><span>RECORD TYPE</span><strong>Synthetic</strong><small>Working system</small></div></div></div></section>
  <section className="case-photo-section"><div className="case-photo" role="img" aria-label="Illustrative EV charging facility at dusk in a European mountain valley"/><span>ILLUSTRATIVE ENERGY-SERVICE SETTING · GENERATED IMAGE</span></section>
  <section className="section-ink case-problem"><div className="container"><Reveal><Kicker number="02" light>THE PRODUCT PROBLEM</Kicker><h2>Business context sits<br/><em>in different places.</em></h2></Reveal><div className="case-columns"><Reveal><div><CircleAlert/><h3>Before</h3><p>Incident details, maintenance evidence, technician availability, service targets, and cost consequences need to be considered together. A generic chat answer would not close the operational loop.</p></div></Reveal><Reveal delay={90}><div><ListChecks/><h3>The design</h3><p>Command assembles evidence and prepares an actionable proposal. A staff member approves the booking. Margin then shows the resulting forecast and, later, the posted actual.</p></div></Reveal><Reveal delay={180}><div><BadgeCheck/><h3>The result</h3><p>A reviewer can perform the entire journey, inspect source records, see persisted changes, reset a private workspace, and trace one work order across both products.</p></div></Reveal></div></div></section>
  <section className="section-paper case-journey"><div className="container"><Reveal><Kicker number="03">THE DECISION TRAIL</Kicker><h2>What the reviewer can <em>verify.</em></h2></Reveal><div className="case-timeline"><div><span>01</span><h3>Report and investigate</h3><p>The incident exists as a database record with asset, site, contract, and history. Analysis cites exact source IDs or falls back conservatively.</p></div><div><span>02</span><h3>Build a proposal</h3><p>Technician skill, availability, service target, and forecast cost are examined. No work order exists yet.</p></div><div><span>03</span><h3>Approve and schedule</h3><p>Staff approval atomically creates the booking, work order, forecast event, and audit entry.</p></div><div><span>04</span><h3>Read the consequence</h3><p>Margin shows the open cost in backlog. Completion posts an actual event and changes actual margin.</p></div></div></div></section>
  <section className="case-proof section-paper"><div className="container"><Reveal><Kicker number="04">ENGINEERING EVIDENCE</Kicker><div className="split-heading"><h2>Built, checked,<br/><em>and observable.</em></h2><p>The repository includes migrations, seed data, architecture notes, a reviewer guide, a captioned walkthrough, and a release gate covering database isolation, domain behavior, builds, and the signed-in browser journey.</p></div></Reveal><div className="proof-links"><a href="https://github.com/code-cra7t/voltaris-energy-platform" target="_blank" rel="noreferrer">Source code <ArrowUpRight/></a><a href="https://github.com/code-cra7t/voltaris-energy-platform/blob/tori/docs/REVIEWER_GUIDE.md" target="_blank" rel="noreferrer">Reviewer guide <ArrowUpRight/></a><a href="https://github.com/code-cra7t/voltaris-energy-platform/actions" target="_blank" rel="noreferrer">Release checks <ArrowUpRight/></a></div><p className="case-disclosure">Voltaris is a fictional European energy-services company. The records, people, sites, and fleet context are synthetic; the applications, data writes, AI calls, and calculations are functional. A real deployment would need enterprise SSO, external integrations, data-protection work, monitoring, and operational safety review.</p></div></section>
  <NextStep eyebrow="MAKE THE DECISION YOURSELF" title="Enter the reviewer workspace." description="A dedicated, isolated shift is ready for the complete incident-to-margin journey." href="/reviewer" label="Launch reviewer workspace"/>
</>; }
