import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BookOpenCheck, CalendarCheck2, FileClock, PlayCircle, ShieldCheck } from "lucide-react";
import { ImageFeature, Kicker, NextStep, PageHero } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Command — AI operations", description: "Evidence-aware service operations with human-approved dispatch and auditable work orders."};

export default function CommandPage() { return <>
  <PageHero number="02" eyebrow="PRODUCT / COMMAND" title="Turn incidents into" accent="informed action" description="Command brings incident context, retrieved knowledge, technician availability, and staff approval into one service workflow." visual={<div className="hero-product-preview"><img src="/media/01-command-incident.jpg" alt="Actual Command application showing the Hannover incident queue"/><span>ACTUAL PRODUCT CAPTURE / COMMAND</span></div>}><div className="product-hero-actions"><a className="button button-light" href="https://voltaris-energy-platform-command.vercel.app/" target="_blank" rel="noreferrer">Launch Command <ArrowUpRight size={18}/></a><a className="play-link" href="/media/walkthrough.mp4" target="_blank" rel="noreferrer"><PlayCircle size={28}/> Watch the workflow</a></div></PageHero>
  <section className="section-paper product-intro"><div className="container"><Reveal><Kicker number="01">THE SERVICE DESK, CONNECTED</Kicker><div className="split-heading"><h2>The next action starts<br/>with the <em>right context.</em></h2><p>For the Hannover connector fault, Command opens the incident alongside asset details, maintenance history, field guidance, and response obligations. The team can move from signal to service without losing the provenance of a decision.</p></div></Reveal><div className="hero-screenshot"><img src="/media/02-command-evidence.jpg" alt="Actual Command evidence and maintenance records for the Hannover charger fault"/><div className="screenshot-caption">ACTUAL PRODUCT CAPTURE / COMMAND EVIDENCE</div></div></div></section>
  <section className="section-ink product-sequence"><div className="container"><Reveal><Kicker number="02" light>THE RESPONSE SEQUENCE</Kicker><h2>Understand. Propose.<br/><em>Approve. Record.</em></h2></Reveal><div className="sequence-grid"><Reveal><div><BookOpenCheck/><span>01 / RETRIEVE</span><h3>Cited evidence</h3><p>Each AI cause and recommended check must cite an exact retrieved source ID. Unsupported claims are discarded.</p></div></Reveal><Reveal delay={60}><div><CalendarCheck2/><span>02 / PLAN</span><h3>Qualified proposal</h3><p>Availability, skill fit, response target, and expected cost inform a proposal without booking anything.</p></div></Reveal><Reveal delay={120}><div><ShieldCheck/><span>03 / AUTHORIZE</span><h3>Human approval</h3><p>A staff member approves the service visit. Booking, work order, forecast, and audit entry commit together.</p></div></Reveal><Reveal delay={180}><div><FileClock/><span>04 / CLOSE</span><h3>Posted actual</h3><p>Completion records a service note and actual cost, which becomes visible to Margin.</p></div></Reveal></div></div></section>
  <section className="section-paper feature-section"><div className="container"><ImageFeature eyebrow="01 / ANALYSIS" title="Sources at the point of judgment." body="Open the source chips on a finding and inspect the underlying maintenance or field record. If the model fails to cite valid evidence, Command displays an explicitly uncertain review rather than an invented diagnosis." image="/media/06-command-analysis.jpg" alt="Command source-backed AI incident analysis"/><ImageFeature reverse eyebrow="02 / EXECUTION" title="A decision with a paper trail." body="After approval, the work order and audit trail show what happened. The field visit is a persisted state change, not a visual mock-up." image="/media/08-command-work-order.jpg" alt="Command approved work order and service details"/></div></section>
  <section className="callout-strip"><div className="container"><span>YOUR DECISION POINT</span><p>Try the fault yourself: analyze it, build a proposal, pause before approval, and inspect what changes after you authorize it.</p><Link href="/reviewer">Open the reviewer journey <ArrowUpRight size={18}/></Link></div></section>
  <NextStep eyebrow="NEXT / MARGIN" title="A work order has a cost." description="Follow the approved service visit into backlog and see how forecast and actual performance stay distinct." href="/margin" label="Explore Margin"/>
</>; }
