import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bot, CircleCheck, Database, ScanSearch, Workflow } from "lucide-react";
import { NetworkVisual } from "@/components/NetworkVisual";
import { PageHero, Kicker, ImageFeature, NextStep } from "@/components/PageParts";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = {title: "Platform", description: "How Voltaris connects evidence, approved energy-service operations, and financial intelligence."};

export default function PlatformPage() { return <>
  <PageHero number="01" eyebrow="THE PLATFORM" title="Operations connected" accent="from end to end" description="An energy-service incident moves through evidence, action, and accounting. Command and Margin make the handoffs visible instead of leaving them between disconnected tools."><Link href="/reviewer" className="button button-primary">Enter the reviewer workspace <ArrowUpRight size={18}/></Link></PageHero>
  <section className="section-paper platform-network"><div className="container"><Reveal><div className="split-heading"><div><Kicker number="01">A SHARED OPERATING PICTURE</Kicker><h2>A network is made of<br/><em>decisions.</em></h2></div><p>Explore the simulated sites below. Each represents context a service team might need to resolve an issue: equipment, maintenance, commitments, people, and costs. The numbers and sites are fictional; the software operations are real.</p></div></Reveal><NetworkVisual/><div className="network-disclosure">SIMULATED NETWORK CONTEXT · NO LIVE CHARGER TELEMETRY OR PHYSICAL CONTROL</div></div></section>
  <section className="section-ink platform-flow"><div className="container"><Reveal><Kicker number="02" light>ONE RECORD / TWO PRODUCTS</Kicker><h2>Every handoff<br/><em>has a consequence.</em></h2></Reveal><div className="flow-chain"><Reveal><div className="flow-item"><ScanSearch/><span>01 / OBSERVE</span><h3>Incident</h3><p>A fault has a place, an asset, a service target, and a history.</p></div></Reveal><Reveal delay={60}><div className="flow-item"><Bot/><span>02 / UNDERSTAND</span><h3>Evidence</h3><p>Command assembles cited context and prepares a response.</p></div></Reveal><Reveal delay={120}><div className="flow-item"><CircleCheck/><span>03 / AUTHORIZE</span><h3>Approval</h3><p>A staff member approves before booking creates a work order.</p></div></Reveal><Reveal delay={180}><div className="flow-item"><Database/><span>04 / ACCOUNT</span><h3>Consequence</h3><p>Margin reads forecast backlog, then actual posted costs.</p></div></Reveal></div></div></section>
  <section className="section-paper feature-section"><div className="container"><Reveal><Kicker number="03">WORKING SURFACES</Kicker><h2>Purpose-built for each side<br/>of the decision.</h2></Reveal><ImageFeature eyebrow="COMMAND / SERVICE OPERATIONS" title="Make the next action defensible." body="The operations workspace grounds recommendations in source records, checks qualified availability, and requires human approval before a dispatch becomes real." image="/media/02-command-evidence.jpg" alt="Command showing source evidence for an incident"><Link className="inline-arrow" href="/command">Discover Command <ArrowRight size={17}/></Link></ImageFeature><ImageFeature reverse eyebrow="MARGIN / OPERATIONS INTELLIGENCE" title="See the cost of doing the work." body="Financial performance and the cost of open service work appear in one place, with forecast clearly separated from booked actuals." image="/media/04-margin-overview.jpg" alt="Margin showing service performance metrics"><Link className="inline-arrow" href="/margin">Discover Margin <ArrowRight size={17}/></Link></ImageFeature></div></section>
  <section className="platform-boundary section-paper"><div className="container"><Reveal><div className="boundary-box"><Workflow size={28}/><div><span className="micro-label">BUILT WITH EXPLICIT BOUNDARIES</span><h2>Advisory intelligence.<br/>Accountable operations.</h2><p>AI can organize evidence and explain calculated results. It cannot silently dispatch a technician, execute generated SQL, or turn a forecast into a posted actual. Those boundaries are encoded in the shared service layer and database transactions.</p></div><Link href="/architecture" aria-label="Explore architecture"><ArrowUpRight/></Link></div></Reveal></div></section>
  <NextStep eyebrow="CONTINUE THE JOURNEY" title="Follow the fault into Command." description="See how a reported fault becomes a source-backed recommendation and an approved service visit." href="/command" label="Explore Command"/>
</>; }
